spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
    username: root
    password: lgbx98356108
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true