#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect